<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDTimeLineData {
    param(
        [Parameter(Mandatory = $true)]
        [string]$RowLabel,

        [Parameter(Mandatory = $false)]
        $BarLabel = $null,

        [Parameter(Mandatory = $false)]
        $Tooltip = $null,

        [Parameter(Mandatory = $true)]
        [DateTime]$Start,

        [Parameter(Mandatory = $true)]
        [DateTime]$End
    )

    End {
        [PSCustomObject]@{
            RowLabel    = $RowLabel
            BarLabel   = $BarLabel
            Tooltip   = $Tooltip

            Start   = $Start
            End   = $End
        }

    }
}
